[package]
name = "gimkit"
version = "0.1.0"
edition = "2021"

[dependencies]
async-recursion = "1.0.5"
chromedriver-manager = "0.2.2"
colored = "2.0.4"
serde_json = "1.0.108"
thirtyfour = "0.31.0"
tokio = { version = "1.34.0", features = ["full"] }
